version: "3"
services:
  app:
    build: .
    depends_on:
      pg-db:
        condition: service_healthy
    ports:
      - 8080:8080
  redis-db:
    image: "redis:latest"
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
  pg-db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssw0rd
      - POSTGRES_DB=training_golang
    volumes:
      - ./data:/var/lib/postgresql/data
    command: -p 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5